// config/permissions.ts

export const PERMISSIONS = {
  ITEM_LIST: 'ITEM_LIST',
  ITEM_DETAIL: 'ITEM_DETAIL',
  ITEM_CREATE: 'ITEM_CREATE',
  ITEM_EDIT: 'ITEM_EDIT',
  ITEM_DEACTIVATE: 'ITEM_DEACTIVATE',
  FAVORITES_USE: 'FAVORITES_USE',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_EDIT: 'PROFILE_EDIT',
  ADMIN_PANEL_VIEW: 'ADMIN_PANEL_VIEW',
};

// Definimos QUÉ permisos tiene cada rol de la base de datos
export const ROLE_PERMISSIONS = {
  // Si la BD dice 'estudiante', le damos estos:
  estudiante: [
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_DETAIL,
    PERMISSIONS.FAVORITES_USE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
  // Si la BD dice 'profesor', le damos estos:
  profesor: [
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_DETAIL,
    PERMISSIONS.ITEM_CREATE,
    PERMISSIONS.ITEM_EDIT,
    PERMISSIONS.ITEM_DEACTIVATE,
    PERMISSIONS.ADMIN_PANEL_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.FAVORITES_USE,
  ],
};